---
title: "Some notes on survey weights"
description: "An area of statistics in which the author is not strong, and really needs to up her game"
date: "2025-09-27"
categories: ["Statistics", "Surveys"]
knitr:
  opts_chunk: 
    dev.args:
      bg: "#00000000"
--- 

<!--------------- my typical setup ----------------->

```{r}
#| label: setup
#| include: false
very_wide <- 500
wide <- 136
narrow <- 76
options(width = narrow)
cache_images <- TRUE
set.seed(1)
blog_dir <- rprojroot::find_root_file(criterion = rprojroot::has_file("_quarto.yml"))
source(fs::path(blog_dir, "shared", "common.R"))
ggplot2::theme_set(theme_custom())
```

<!--------------- post begins here ----------------->

🫀 : Okay. So. Um. Hey babe. You know that [GAMLSS regression post](/posts/2025-09-07_gamlss/) we wrote? <br>

🧠 : Do you mean the monstrosity that took an entire month out of our lives, spawned an unhinged prequel post about the [Box-Cox power exponential distribution](/posts/2025-08-02_box-cox-power-exponential/) and then *another* unhinged prequel post about [B-splines and P-splines](/posts/2025-09-06_p-splines/)? The one that brought us to tears several times and made us question our entire reason for being? The one that literally gave you nightmares? The accursed one, the post we swore we were finished with and would never ever revisit upon pain of death. Is **that** the post you mean? <br>

🫀 : Uh, yeah.<br>

🧠 : Oh yes, I remember it. What about it? <br>

🫀 : I, um... look... I think it, uhhhhh... needs a sequel post. We should talk about survey weights. I mean, I know it's not our job to talk about all the things, but it does sort of matter right? And we've come so far with this thing, we should finish the job properly, right? I mean, I know we're not getting paid for this, but you *do* like to do a good job with things right? Just one more post? Please????<br>

🧠 : ... <br>

🫀 : ... <br>

🧠 : Girl. Seriously though. What the actual fuck is wrong with you?

<br><br>


- NHANES. In an earlier [post](/posts/2025-09-07_gamlss/) I talked about the [National Health and Nutrition Examination Survey](https://www.cdc.gov/nchs/nhanes/) (NHANES). Weights discussed in the [NHANES study design tutorial](https://wwwn.cdc.gov/nchs/nhanes/tutorials/sampledesign.aspx) 

- SIH. [Survey of Income and Housing](https://www.abs.gov.au/statistics/detailed-methodology-information/concepts-sources-methods/survey-income-and-housing-user-guide-australia/2019-20) has a [weights](https://www.abs.gov.au/statistics/detailed-methodology-information/concepts-sources-methods/survey-income-and-housing-user-guide-australia/2019-20/weights) page

## References

- The [survey](https://cran.r-project.org/package=survey) R package by Thomas Lumley

- [How to weight a survey](https://bookdown.org/jespasareig/Book_How_to_weight_a_survey/) by Josep Espasa Reig

- [How different weighting methods work](https://www.pewresearch.org/methods/2018/01/26/how-different-weighting-methods-work/) from the Pew Research Center

- [Survey analysis](https://epirhandbook.com/en/new_pages/survey_analysis.html) chapter from The Epidemiologist R handbook