---
title: "Bayesian Emax regression using brms"
description: "This is a subtitle"
date: "2025-02-21"
--- 

<!--------------- my typical setup ----------------->

```{r}
#| label: setup
#| include: false
very_wide <- 500
wide <- 136
narrow <- 76
options(width = narrow)
cache_images <- TRUE
set.seed(1)
```

<!--------------- post begins here ----------------->

```{r}
#| label: packages
#| message: false
library(brms)
library(dplyr)
library(tibble)
library(ggplot2)
library(tidybayes)
```

```{r}
#| label: binary-data
dat <- BayesERtools::d_sim_binom_cov_hgly2
```

```{r}
#| label: binary-emax
#| cache: true
#| message: false
#| results: hide
mod <- brm(
  formula = brmsformula(
    AEFLAG ~ e0 + emax * AUCss / (ec50 + AUCss),
    e0 + emax + ec50 ~ 1,
    nl = TRUE
  ),
  family = bernoulli(),
  data = dat,
  prior = c(
    prior(normal(0, 5), nlpar = "e0"),
    prior(normal(0, 5), nlpar = "emax"),
    prior(normal(2000, 500), nlpar = "ec50", lb = 0)
  )
)
```

```{r}
#| label: plot
mod |>
  epred_draws(newdata = tibble(AUCss = seq(0, 10000, 100))) |>
  ungroup() |>
  summarise(AEPROB = mean(.epred), .by = AUCss) |> 
  ggplot(aes(AUCss, AEPROB)) + 
  geom_path() + 
  geom_jitter(
    mapping = aes(AUCss, AEFLAG), 
    data = dat |> mutate(AEFLAG = ifelse(AEFLAG == 1, 1.125, -0.125)), 
    height = 0.075, 
    width = 0
  ) +
  scale_y_continuous(breaks = seq(0, 1, 0.2), limits = c(-0.2, 1.2)) + 
  theme_bw()
```

